.viperlightignore
Add content scanner ignore for public email address.
=> Ignore public email address in Python package

buildspec.yml
*Issue #, if available:* #113
Change to deployment folder for build since unit tests are running last.
=> PR for #113

buildspec.yml
*Issue #, if available:* #113
Build dependencies weren't being staged for pipeline build.
=> Add build dependencies

deployment/Dockerfile, source/control-panel/package-lock.json, source/sample-waiting-room-site/src/views/CheckOut.vue, source/sample-waiting-room-site/src/views/WaitingRoom.vue
*Issue #, if available:* #113
Change to gallery.ecr.aws for image pulls
Change jwcrypto layer build to Amazon Linux 2
Fix some routing bugs in sample waiting room
=> Layer build changes and sample fixes

README.md, deployment/deploy.sh
Documentation and copyright updates
=> Update Copyrights and instructions in README

source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json
Update dependencies for glob-parent and ansi-html.
=> Updated dependencies for dependabot

deployment/aws-virtual-waiting-room-sample-inlet-strategy.json, deployment/aws-virtual-waiting-room.json
Removed default parameters in core and sample inlet.
=> remove default parameters

source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json
Dependency updates for control panel and waiting room samples.
=> Sample app dependency updates

README.md
=> Fix landing page link

README.md
Add link to implementation guide to top of readme header.
=> Add implementation guide link to header

README.md, deployment/aws-virtual-waiting-room-getting-started.json, deployment/build-s3-dist.sh
Better build support for nested templates.
Improve build and deploy instructions in README.
=> Feature/nested v1.0.1

NOTICE.txt, README.md, docs/developer-guide.md, docs/install-guide.md, docs/software-architecture.md, source/shared/aws-virtual-waiting-room-common/README.md
**Note: this PR is being merged directly to main. Merge to 1.1.0 branches as needed.**
*Issue #, if available:* #146
Renaming content for the solution name change (no code)
=> Renaming content #146

.github/workflows/notify-workflow.yml
=> Modify notify workflow

deployment/end-workflow-notification.py
edit end workflow notification file
=> end-workflow file

deployment/virtual-waiting-room-on-aws.json, source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json
#133
Introduce a custom lambda resource to clip the stack name to satisfy the service quotas for the SQS name
=> Custom resource to clip strings to satisfy the service quotas for SQS

deployment/virtual-waiting-room-on-aws.json
*Issue #, if available:* #170
Add suppressions for Lambda VPC and concurrent executions false positives.
=> Add cfn_nag suppressions to Lambda #170

buildspec.yml
*Issue #, if available:* #170
Update artifact file list for recently added pipeline tools 
=> Add required files to buildspec.yml #170

NOTICE.txt
#179 
Update licenses of third-party packages
=> Update NOTICE.txt with latest licenses #179

source/control-panel/package-lock.json, source/control-panel/package.json, source/sample-waiting-room-site/package-lock.json
Build pipeline called-out eslint for update
Other UI dependencies updated to compatible versions
=> Dependency update for UI samples

sonar-project.properties
Update SQ properties file for source scan
=> Update SQ properties file for source scan

sonar-project.properties
Update source locations for SQ
=> Update source locations for SQ

CHANGELOG.md, buildspec.yml, sonar-project.properties
Update source locations for SQ; add projected date to CHANGELOG for pipeline
=> Update for pipeline build

sonar-project.properties
Add SQ ignore for chalice/vendor folders
=> Updates for SQ and pipeline

sonar-project.properties
=> Updates for SQ

source/control-panel/src/App.vue, source/control-panel/src/components/Credentials.vue, source/core-api-authorizers-sample/www/waitingroom/index.html, source/core-api/lambda_functions/assign_queue_num.py, source/core-api/lambda_functions/generate_token_base.py, source/openid-waitingroom/chalice/app.py, source/openid-waitingroom/www/login.html
#193
Updates for issues called-out by SonarQube.
=> SQ issues v1.1.0

.github/workflows/pull-request-workflow.yml, .github/workflows/push-workflow.yml, README.md, buildspec.yml, deployment/build-s3-dist.sh, deployment/deploy.sh, source/core-api/custom_resources/initialize_state.py, source/openid-waitingroom/chalice/app.py, source/sample-inlet-strategies/max_size_inlet.py, source/sample-inlet-strategies/periodic_inlet.py, source/shared/virtual-waiting-room-on-aws-common/setup.py, source/shared/virtual-waiting-room-on-aws-common/vwr/common/jwt.py, source/shared/virtual-waiting-room-on-aws-common/vwr/common/sanitize.py, source/token-authorizer/chalice/app.py
- Install vwr common package before running unit tests
- Upgrade common package version to 1.1.0
- Change nodejs version in build spec to ver. 16
- Include timeouts to address pylint issues
=> Fix pipeline issues and upgrade Node.js

buildspec.yml
=> Use Node.js 14

.gitignore, deployment/requirements.txt, deployment/run-unit-tests.sh, docs/software-architecture.md, sonar-project.properties
Add provision for coverage reporting 
Include notes in software architecture for queue position expiry
=> Coverage reporting

.github/workflows/notify-workflow.yml, .github/workflows/post-pipeline-workflow.yml, .github/workflows/pull-request-workflow.yml, .github/workflows/push-workflow.yml
Workflow and dependency installation changes
=> dependency updates for workflows

source/core-api-authorizers-sample/www/waitingroom/index.html, source/core-api/lambda_functions/assign_queue_num.py, source/core-api/lambda_functions/generate_token_base.py, source/openid-waitingroom/www/login.html, source/sample-waiting-room-site/src/components/AuthorizationToken.vue
Updates for last of the SQ issues
=> Updates for SQ issues

sonar-project.properties
Updates for code coverage
Update sonar-project.properties for exclusions (*.vue files)
=> Updates for code coverage

sonar-project.properties
=> Updates for SQ code coverage

NOTICE.txt, source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json
Update licenses in NOTICE.txt
Update npm dependencies for control-panel and sample-waiting-room-site
=> Update npm dependencies; update LICENSE.txt

source/control-panel/package.json, source/sample-waiting-room-site/package.json
Add attributes description, author, license
=> Add required package.json attributes for build pipeline

CHANGELOG.md, CONTRIBUTING.md
Informational file updates for upcoming release
=> Informational file updates for upcoming release

CHANGELOG.md, CONTRIBUTING.md, NOTICE.txt, source/control-panel/package-lock.json, source/control-panel/package.json, source/sample-waiting-room-site/package-lock.json, source/sample-waiting-room-site/package.json
Minor updates to various config and informational files
Updating license declaration file
=> Incremental PR to release for v1.1.0

deployment/run-unit-tests.sh, sonar-project.properties, source/sample-inlet-strategies/inlet_strategy_tests.py
Add'l unit tests for inlet strategies
=> Add'l unit tests for inlet strategies

deployment/run-unit-tests.sh
Update execute permissions for run_unit_tests script
=> Update execute permissions

deployment/run-unit-tests.sh, source/openid-waitingroom/chalice/openid_waitingroom_tests.py
Update to openid waitingroom tests
=> Update to openid waitingroom tests

deployment/run-unit-tests.sh, source/openid-waitingroom/chalice/openid_waitingroom_tests.py
=> Incremental update to release

sonar-project.properties
Update to coverage report locations
=> Update to coverage report locations

deployment/run-unit-tests.sh, sonar-project.properties, source/shared/virtual-waiting-room-on-aws-common/common_tests.py
Update unit tests for common code
=> Update unit tests for common code

deployment/run-unit-tests.sh, sonar-project.properties, source/core-api-authorizers-sample/chalice/sample_api_tests.py, source/shared/shared_resources_tests.py
Update unit tests for API samples
=> Update unit tests for API samples

source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json
=> Change for loader-utils dependency update

source/openid-waitingroom/chalice/app.py, source/token-authorizer/chalice/token_authorizer_tests.py
Fix token/claims comparison when handling the /userInfo API endpoint
=> Merge OpenID userInfo fix to develop

source/control-panel/src/components/IncrementServingCounter.vue
None.
Made it possible to change the increment value of the Serving Counter to any value. You can also specify a negative value to decrease the Serving Counter.
=> Change any increment serving counter.

README.md, buildspec.yml, deployment/build-s3-dist.sh, source/shared/virtual-waiting-room-on-aws-common/setup.py
Update version numbers for v1.1.1 release.
=> Update version numbers for v1.1.1 release

CHANGELOG.md
=> Update CHANGELOG release date

CHANGELOG.md
=> Additions to CHANGELOG

.gitignore, CHANGELOG.md, README.md, deployment/build-s3-dist.sh, deployment/run-unit-tests.sh, deployment/virtual-waiting-room-on-aws.json, source/control-panel/package-lock.json, source/control-panel/package.json, source/control-panel/src/components/ActiveTokens.vue, source/control-panel/src/components/ExpiredTokens.vue, source/control-panel/src/components/ServingCounter.vue, source/control-panel/src/components/WaitingRoomSize.vue, source/control-panel/src/main.js, source/core-api/lambda_functions/counters.py, source/core-api/lambda_functions/get_list_expired_tokens.py, source/core-api/lambda_functions/get_num_active_tokens.py, source/core-api/lambda_functions/get_waiting_num.py, source/core-api/lambda_functions/lambda_functions_tests.py, source/core-api/lambda_functions/reset_initial_state.py, source/core-api/lambda_functions/set_max_queue_position_expired.py, source/openid-waitingroom/chalice/app.py, source/sample-waiting-room-site/package-lock.json, source/sample-waiting-room-site/src/components/MyPosition.vue, source/sample-waiting-room-site/src/components/ServingPosition.vue, source/sample-waiting-room-site/src/components/WaitingRoomSize.vue, source/sample-waiting-room-site/src/views/WaitingRoom.vue, source/shared/virtual-waiting-room-on-aws-common/setup.py
Release 1.1.3
+ Added available Servings info to Control Panel UI [#232](https://github.com/aws-solutions/virtual-waiting-room-on-aws/pull/232).
+ Fixed expired queue positions persist in the Virtual Waiting Room size [#208](https://github.com/aws-solutions/virtual-waiting-room-on-aws/issues/208).
+ Fixed /queue_num endpoint returns outdated results even after a reset [#214](https://github.com/aws-solutions/virtual-waiting-room-on-aws/issues/214).
+ Fixed intermittent failures in OpenID adapter's /userInfo endpoint [#231](https://github.com/aws-solutions/virtual-waiting-room-on-aws/issues/231).
+ Fixed /expired_tokens endpoint bug when LastEvaluatedKey is present in query response …
=> Update to version v1.1.3

.gitignore, CHANGELOG.md, deployment/build-open-source-dist.sh, deployment/build-s3-dist.sh, deployment/run-unit-tests.sh, source/control-panel/package-lock.json, source/sample-waiting-room-site/package-lock.json, source/shared/virtual-waiting-room-on-aws-common/setup.py
Description of changes:
**Release 1.1.4**
- Updated webpack-dev-middleware from 5.3.3 to 5.3.4 to resolve security vulnerability [CVE-2024-29180]
- Updated express from 4.18.1 to 4.19.2 to resolve security vulnerability [CVE-2024-29041]
- Updated follow-redirects from 1.15.4 to 1.15.6 to resolve security vulnerability [CVE-2024-28849]
=> Update to version v1.1.4

.gitignore, CHANGELOG.md, deployment/Dockerfile, deployment/build-s3-dist.sh, deployment/requirements.txt, deployment/run-unit-tests.sh, source/control-panel/package-lock.json, source/core-api/custom_resources/requirements.txt, source/openid-waitingroom/chalice/requirements.txt, source/openid-waitingroom/custom_resources/requirements.txt, source/sample-waiting-room-site/package-lock.json, source/shared/virtual-waiting-room-on-aws-common/setup.py, source/token-authorizer/chalice/requirements.txt
n/a
- `ws` to mitigate [CVE-2024-37890]
- `braces` from 3.0.2 to 3.0.3 to mitigate [CVE-2024-4068]
- `urllib3` to `2.2.2` to mitigate [CVE-2024-37891]
=> Release 1.1.5

CHANGELOG.md, deployment/build-s3-dist.sh, deployment/run-unit-tests.sh, source/sample-waiting-room-site/package-lock.json, source/sample-waiting-room-site/package.json, source/shared/virtual-waiting-room-on-aws-common/setup.py
- Bump `axios` to mitigate [CVE-2024-39338]
=> Update to version v1.1.7

CHANGELOG.md, deployment/build-s3-dist.sh, deployment/run-unit-tests.sh, source/control-panel/package-lock.json, source/control-panel/package.json, source/sample-waiting-room-site/package-lock.json, source/sample-waiting-room-site/package.json, source/shared/virtual-waiting-room-on-aws-common/setup.py
- `micromatch` to mitigate [CVE-2024-4067]
- `webpack` to mitigate [CVE-2024-43788]
- `express` to mitigate [CVE-2024-43796]
- `send` to mitigate [CVE-2024-43799]
- `serve-static` to mitigate [CVE-2024-43800]
- `body-parser` to mitigate [CVE-2024-45590]
=> Update to version v1.1.8

README.md
Update README.md file for Solution Retirement
=> Updated README for Retirement Notice
